INSERT INTO Client (Nom,Prenom,Pt_Fidelite,Age,Mail,Num_Tel,ID,MDP,STATUT) VALUES
    ('Dupont', 'Jean', NULL, 3000, NULL, NULL,'JDupont','21232f297a57a5a743894a0e4a801fc3','Admin'), --admin
    ('Martin', 'Marie', 0, 28, 'marie.martin@mail.com', '0602030405','MMartin','f02368945726d5fc2a14eb576f7276c0','Client'), --bonjour
    ('Bernard', 'Paul', 0, 42, 'paul.bernard@mail.com', '0603040506','PBernard','f02368945726d5fc2a14eb576f7276c0','Client'), --bonjour
    ('Dubois', 'Pierre', 0, 31, 'pierre.dubois@mail.com', '0604050607','PDubois','ab4f63f9ac65152575886860dde480a1','Client'), --azerty
    ('Durand', 'Luc', 0, 45, 'luc.durand@mail.com', '0605060708','LDurand','ab4f63f9ac65152575886860dde480a1','Client'), --azerty
    ('Lefevre', 'Sophie', 0, 29, 'sophie.lefevre@mail.com', '0606070809','SLefevre','ab4f63f9ac65152575886860dde480a1','Client'),  --azerty
    ('Moreau', 'Pierre', 0, 39, 'pierre.moreau@mail.com', '0607080910','PMoreau','70d4539ead3248bd4b79ede8ad3954ea','Client'), --shreckislove
    ('Simon', 'Claire', 0, 33, 'claire.simon@mail.com', '0608091011','CSimon','70d4539ead3248bd4b79ede8ad3954ea','Client'), --shreckislove
    ('Laurent', 'Nicolas', 0, 27, 'nicolas.laurent@mail.com', '0609101112','NLaurent','70d4539ead3248bd4b79ede8ad3954ea','Client'); --shreckislove

INSERT INTO Paiement VALUES
    (1, 'Carte bancaire'),
    (2, 'Chèque'),
    (3, 'Espèces');


INSERT INTO Danger VALUES
    (1, 'Allergènes non indiqués', 'S''assurer que l''étiquetage des produits mentionne clairement les allergènes courants tels que les arachides, le gluten, et le lactose'),
    (2, 'Contamination croisée', 'Utiliser des espaces de stockage séparés pour les produits crus et cuits, et nettoyer régulièrement les surfaces de travail'),
    (3, 'Mauvaise conservation des produits frais', 'Respecter les températures de conservation pour les produits frais, réfrigérés ou surgelés'),
    (4, 'Emballage endommagé', 'Vérifier les emballages pour s''assurer qu''ils ne sont pas perforés ou abîmés, ce qui pourrait entraîner une contamination'),
    (5, 'Produits chimiques dangereux', 'Stocker les produits chimiques ménagers loin des denrées alimentaires et respecter les consignes de sécurité pour leur manipulation'),
    (6, 'Étiquetage erroné', 'Vérifier que toutes les informations sur l''étiquette, comme les ingrédients et la date de péremption, sont correctes'),
    (7, 'Produits inflammables', 'Conserver les produits inflammables, tels que les aérosols ou les alcools forts, dans des zones sûres et bien ventilées'),
    (8, 'Réactions à des additifs alimentaires', 'Informer les clients des risques potentiels liés aux additifs comme les conservateurs et les colorants artificiels'),
    (9, 'Défaut de traçabilité', 'S assurer que chaque lot de produits dispose d''une traçabilité claire pour faciliter les rappels en cas de problème sanitaire'),
    (10, 'Usage incorrect des produits ménagers', 'Indiquer clairement les instructions d''utilisation sur les produits ménagers pour éviter tout risque d''intoxication ou de brûlure');

INSERT INTO Categorie VALUES
    (1, 'Alimentation', 'Frais'),
    (2, 'Alimentation', 'Épicerie'),
    (3, 'Alimentation', 'Surgelés'),
    (4, 'Boissons', 'Non alcoolisées'),
    (5, 'Boissons', 'Alcoolisées'),
    (6, 'Hygiène et beauté', 'Soins du corps'),
    (7, 'Hygiène et beauté', 'Cheveux'),
    (8, 'Produits ménagers', 'Entretien des sols'),
    (9, 'Produits ménagers', 'Lessive'),
    (10, 'Produits bébé', 'Alimentation infantile'),
    (11, 'Produits bébé', 'Soins et hygiène bébé'),
    (12, 'Animaux', 'Alimentation pour animaux'),
    (13, 'Animaux', 'Accessoires pour animaux'),
    (14, 'Maison et décoration', 'Vaisselle et ustensiles'),
    (15, 'Maison et décoration', 'Décoration intérieure'),
    (16, 'Bricolage', 'Peinture'),
    (17, 'Bricolage', 'Outils'),
    (18, 'Papeterie et bureautique', 'Fournitures scolaires'),
    (19, 'Papeterie et bureautique', 'Matériel de bureau'),
    (20, 'Vêtements et accessoires', 'Homme'),
    (21, 'Vêtements et accessoires', 'Femme'),
    (22, 'Vêtements et accessoires', 'Enfant');

INSERT INTO Description (Nom,Marque,Description,Prix,Num_Danger,Num_Categorie) VALUES
    ('Pâtes', 'Barilla', 'Pâtes longues de type spaghetti', 1.50, 3, 2),
    ('Lait', 'Lactel', 'Lait entier pasteurisé 1L', 0.90, 3, 1),
    ('Jus d''orange', 'Tropicana', 'Jus d''orange pressé sans pulpe 1L', 2.30, 3, 4),
    ('Pain de mie', 'Harry''s', 'Pain de mie complet', 1.80, 1, 2),
    ('Riz', 'Uncle Ben''s', 'Riz basmati, 500g', 2.50, 3, 2),
    ('Céréales', 'Kellogg''s', 'Céréales Corn Flakes, 375g', 3.20, 1, 2),
    ('Savon', 'Dove', 'Savon hydratant 100g', 1.25, 10, 6),
    ('Dentifrice', 'Colgate', 'Dentifrice blanchissant 75ml', 2.10, 10, 6),
    ('Fromage', 'Président', 'Camembert au lait cru', 3.00, 3, 1),
    ('Coca-Cola', 'Coca-Cola', 'Boisson gazeuse 1,5L', 1.75, 7, 4),
    ('Yaourt nature', 'Yoplait', 'Yaourt nature 4x125g', 1.90, 3, 1),
    ('Chocolat noir', 'Lindt', 'Tablette de chocolat noir 70%, 100g', 2.90, 1, 2),
    ('Biscuits', 'LU', 'Petits beurres, 250g', 1.60, 1, 2),
    ('Eau minérale', 'Evian', 'Eau minérale naturelle 1,5L', 0.85, 7, 4),
    ('Beurre', 'Président', 'Beurre doux 250g', 2.40, 3, 1),
    ('Poulet rôti', 'Supermarché', 'Poulet rôti prêt à consommer', 8.50, 3, 1),
    ('Huile d''olive', 'Puget', 'Huile d''olive vierge extra 500ml', 6.20, 3, 2),
    ('Lessive liquide', 'Ariel', 'Lessive liquide pour textiles colorés 1,5L', 7.50, 5, 9),
    ('Shampooing', 'Garnier', 'Shampooing fortifiant 250ml', 3.40, 10, 7),
    ('Œufs', 'Matines', 'Œufs de poules élevées en plein air, boîte de 12', 2.80, 3, 1),
    ('Pizza surgelée', 'Buitoni', 'Pizza 4 fromages surgelée', 4.90, 3, 3),
    ('Crème hydratante', 'Nivea', 'Crème hydratante pour le corps, 150ml', 3.90, 10, 6),
    ('Saucisses', 'Herta', 'Saucisses de Francfort, 6 unités', 3.20, 3, 1),
    ('Détergent sol', 'Mr. Propre', 'Détergent pour sols, 1L', 2.60, 5, 8),
    ('Chips', 'Lay''s', 'Chips nature, 300g', 2.50, 1, 2),
    ('Bière', 'Heineken', 'Bière blonde 6x33cl', 5.90, 7, 5),
    ('Lentilles', 'Bonduelle', 'Lentilles en conserve, 400g', 1.40, 3, 2),
    ('Savon liquide', 'Le Petit Marseillais', 'Savon liquide 300ml', 2.80, 10, 6),
    ('Café moulu', 'Carte Noire', 'Café moulu, 250g', 4.50, 1, 2),
    ('Nettoyant multi-usages', 'Cif', 'Nettoyant multi-usages 750ml', 3.00, 5, 8),
    ('Miel', 'Lune de Miel', 'Miel toutes fleurs 500g', 4.90, 1, 2),
    ('Sardines', 'Connétable', 'Sardines à l''huile, boîte de 120g', 2.60, 3, 2),
    ('Papier toilette', 'Lotus', 'Papier toilette, 12 rouleaux', 4.20, 5, 9),
    ('Gel douche', 'Axe', 'Gel douche, 250ml', 2.50, 10, 6),
    ('Bâtonnets de poisson', 'Findus', 'Bâtonnets de poisson, 10 unités', 4.80, 3, 3),
    ('Jambon cuit', 'Fleury Michon', 'Jambon cuit découenné, 4 tranches', 3.80, 3, 1),
    ('Margarine', 'Fruit d''Or', 'Margarine allégée, 500g', 3.30, 3, 1),
    ('Moutarde', 'Amora', 'Moutarde de Dijon, 250g', 1.40, 1, 2),
    ('Liquide vaisselle', 'Paic', 'Liquide vaisselle citron, 500ml', 2.00, 5, 8),
    ('Coton-tiges', 'Johnson & Johnson', 'Boîte de 200 coton-tiges', 1.70, 10, 6),
    ('Sirop de menthe', 'Teisseire', 'Sirop de menthe, 700ml', 3.20, 1, 4),
    ('Yaourt aux fruits', 'Danone', 'Yaourts aux fruits, 4x125g', 2.40, 3, 1),
    ('Croquettes pour chat', 'Whiskas', 'Croquettes poulet, 2kg', 6.90, 3, 12),
    ('Riz basmati', 'Tilda', 'Riz basmati, 1kg', 3.50, 3, 2),
    ('Saucisson sec', 'Justin Bridou', 'Saucisson sec, 250g', 4.50, 3, 1),
    ('Nettoyant vitres', 'Ajax', 'Nettoyant pour vitres, 750ml', 2.90, 5, 8),
    ('Poisson surgelé', 'Capitaine Iglo', 'Filets de colin, 400g', 5.40, 3, 3),
    ('Gel coiffant', 'L''Oréal', 'Gel coiffant fixation forte, 150ml', 4.10, 10, 7),
    ('Savon vaisselle', 'Mir', 'Savon vaisselle citron, 750ml', 2.20, 5, 8),
    ('Croissants', 'Pasquier', 'Croissants pur beurre, 6 unités', 3.50, 1, 2),
    ('Biscottes', 'Jacquet', 'Biscottes complètes, 300g', 1.90, 1, 2),
    ('Tisane', 'Lipton', 'Tisane à la menthe, 20 sachets', 2.70, 1, 4),
    ('Tomates en conserve', 'Conforama', 'Tomates pelées, 400g', 1.60, 3, 2),
    ('Sauce tomate', 'Panzani', 'Sauce tomate basilic, 500ml', 2.40, 1, 2),
    ('Huile de tournesol', 'Lesieur', 'Huile de tournesol, 1L', 3.10, 3, 2),
    ('Pâtes à tartiner', 'Nutella', 'Pâte à tartiner chocolat noisettes, 400g', 4.20, 1, 2),
    ('Lait en poudre', 'Nestlé', 'Lait en poudre entier, 500g', 6.00, 3, 1),
    ('Purée de pommes', 'Andros', 'Purée de pommes, 4x100g', 2.80, 3, 1),
    ('Lait de coco', 'Goya', 'Lait de coco, 400ml', 2.50, 3, 2),
    ('Tarte aux pommes', 'Croustipate', 'Tarte aux pommes, 1 unité', 3.40, 1, 2),
    ('Brioche', 'Gontran Cherrier', 'Brioche pur beurre, 500g', 4.00, 1, 2),
    ('Lait de soja', 'Alpro', 'Lait de soja nature, 1L', 2.20, 3, 1),
    ('Café en grains', 'Illy', 'Café en grains, 250g', 5.90, 1, 2),
    ('Bonbons', 'Haribo', 'Bonbons au goût fruité, 200g', 2.50, 1, 2),
    ('Margarine', 'St Hubert', 'Margarine 500g', 2.80, 3, 1),
    ('Glaçons', 'Supermarché', 'Glaçons en sachet, 2kg', 1.90, 3, 3),
    ('Bouillon cube', 'Maggi', 'Bouillon cube légumes, 12 unités', 1.60, 3, 2),
    ('Chips', 'Pringles', 'Chips saveur originale, 200g', 2.80, 1, 2),
    ('Yaourt grec', 'Fage', 'Yaourt grec nature, 500g', 2.90, 3, 1),
    ('Gaufres', 'Lu', 'Gaufres fourrées chocolat, 6 unités', 3.50, 1, 2),
    ('Soda', 'Pepsi', 'Soda cola, 1,5L', 1.80, 7, 4),
    ('Riz à sushi', 'Kokuho', 'Riz à sushi, 500g', 4.10, 3, 2),
    ('Muesli', 'Nestlé', 'Muesli aux fruits, 500g', 3.60, 1, 2),
    ('Crêpes', 'Bord Bia', 'Crêpes nature, 6 unités', 2.70, 1, 2),
    ('Tapis de bain', 'Supermarché', 'Tapis de bain en coton', 6.50, 10, 8),
    ('Déodorant', 'Nivea', 'Déodorant roll-on, 50ml', 3.20, 10, 6),
    ('Pâtes à pizza', 'Panzani', 'Pâtes à pizza prêtes à l''emploi, 250g', 1.80, 1, 2),
    ('Gobelets en plastique', 'Supermarché', 'Gobelets en plastique, 50 unités', 1.50, 5, 9),
    ('Mélange pour gâteau', 'Betty Crocker', 'Mélange pour gâteau au chocolat, 450g', 1.8, 1, 2),
    ('Sauce soja', 'Kikkoman', 'Sauce soja, 250ml', 2.30, 1, 2),
    ('Lait concentré', 'Nestlé', 'Lait concentré sucré, 397g', 2.80, 3, 1),
    ('Mélange de fruits secs', 'Dakatine', 'Mélange de fruits secs, 200g', 3.90, 1, 2),
    ('Crème de fraîche', 'Elle & Vire', 'Crème de fraîche épaisse, 200g', 2.20, 3, 1),
    ('Moutarde', 'Maille', 'Moutarde douce, 200g', 1.80, 1, 2),
    ('Vinaigre balsamique', 'Ponti', 'Vinaigre balsamique, 500ml', 3.00, 1, 2),
    ('Yaourt à boire', 'Yoplait', 'Yaourt à boire nature, 4x100ml', 2.30, 3, 1),
    ('Gelée de fruits', 'Andros', 'Gelée de fruits, 450g', 2.50, 1, 2),
    ('Compote de pommes', 'Andros', 'Compote de pommes, 4x100g', 2.10, 3, 1),
    ('Chocolat au lait', 'Milka', 'Tablette de chocolat au lait, 100g', 2.70, 1, 2),
    ('Bière sans alcool', 'Heineken', 'Bière sans alcool, 6x33cl', 5.50, 7, 5),
    ('Pâtes fraîches', 'Rana', 'Pâtes fraîches ravioli, 250g', 3.40, 1, 2),
    ('Purée de tomate', 'Herta', 'Purée de tomate, 500g', 2.20, 3, 2),
    ('Huile de colza', 'Lesieur', 'Huile de colza, 1L', 3.40, 3, 2),
    ('Pâte à tartiner', 'Bonne Maman', 'Pâte à tartiner fruits rouges, 350g', 4.00, 1, 2),
    ('Confiture', 'Bonne Maman', 'Confiture d''abricots, 370g', 3.60, 1, 2),
    ('Épices', 'Ducros', 'Épices pour curry, 40g', 1.80, 1, 2),
    ('Amandes', 'Vahiné', 'Amandes entières, 200g', 3.30, 1, 2),
    ('Thé', 'Lipton', 'Thé noir, 25 sachets', 2.20, 1, 4),
    ('Saucisses de Toulouse', 'Herta', 'Saucisses de Toulouse, 4 unités', 4.20, 3, 1),
    ('Raisins secs', 'Dole', 'Raisins secs, 250g', 2.70, 1, 2),
    ('Crème solaire', 'Nivea', 'Crème solaire SPF 30, 200ml', 8.90, 10, 6),
    ('Barres chocolatées', 'Mars', 'Barres chocolatées, 6 unités', 3.90, 1, 2),
    ('Pain complet', 'Brioche Pasquier', 'Pain complet, 500g', 2.00, 1, 2),
    ('Lait d''amande', 'Alpro', 'Lait d''amande, 1L', 2.50, 3, 1),
    ('Pâtes de fruits', 'Lutti', 'Pâtes de fruits variées, 200g', 2.20, 1, 2),
    ('Fromage blanc', 'Yoplait', 'Fromage blanc nature, 500g', 2.40, 3, 1),
    ('Pâtes à tarte', 'Croustipate', 'Pâtes à tarte brisée, 1 unité', 2.70, 1, 2),
    ('Poireaux', 'Supermarché', 'Poireaux frais, 1 botte', 1.80, 3, 11),
    ('Pommes de terre', 'Supermarché', 'Pommes de terre, 2kg', 3.00, 3, 11),
    ('Café décaféiné', 'Senso', 'Café décaféiné, 250g', 5.20, 1, 2),
    ('Conserve de haricots verts', 'Bonduelle', 'Haricots verts, 400g', 1.80, 3, 2),
    ('Miel de fleurs', 'Miel & Co', 'Miel de fleurs, 500g', 4.50, 1, 2),
    ('Trousse de toilette', 'Supermarché', 'Trousse de toilette en nylon', 4.00, 10, 8),
    ('Papier aluminium', 'Supermarché', 'Papier aluminium, 25m', 2.50, 5, 9),
    ('Gant de cuisine', 'Supermarché', 'Gant de cuisine en coton', 1.80, 10, 8),
    ('Sac poubelle', 'Supermarché', 'Sac poubelle grand format, 20 unités', 3.30, 5, 9),
    ('Crème anti-rides', 'L''Oréal', 'Crème anti-rides, 50ml', 12.50, 10, 6),
    ('Syrup', 'Teisseire', 'Syrup fraise, 700ml', 3.00, 1, 4),
    ('Pâtes à tartiner', 'Jif', 'Pâte à tartiner caramel, 400g', 4.00, 1, 2),
    ('Gel nettoyant', 'La Roche-Posay', 'Gel nettoyant doux, 200ml', 7.20, 10, 6),
    ('Papier sulfurisé', 'Supermarché', 'Papier sulfurisé, 10m', 1.90, 5, 9),
    ('Feuilles de laurier', 'Ducros', 'Feuilles de laurier séchées, 20g', 1.70, 1, 2),
    ('Sachet de thé', 'Twinings', 'Sachet de thé Earl Grey, 20 unités', 3.00, 1, 4),
    ('Sac à dos', 'Supermarché', 'Sac à dos en polyester', 15.00, 10, 8),
    ('Filtre à café', 'Melitta', 'Filtre à café, 100 unités', 2.20, 1, 2),
    ('Gel douche', 'Dove', 'Gel douche hydratant, 250ml', 3.10, 10, 6),
    ('Lait pour bébé', 'Lactalis', 'Lait pour bébé 1er âge, 800g', 12.00, 3, 1),
    ('Papier cadeau', 'Supermarché', 'Papier cadeau, 5m', 1.60, 5, 9),
    ('Pain au chocolat', 'Pasquier', 'Pain au chocolat, 4 unités', 2.50, 1, 2),
    ('Bouteille d''eau', 'Contrex', 'Bouteille d''eau minérale, 1,5L', 1.00, 7, 4),
    ('Crème de jour', 'Nivea', 'Crème de jour hydratante, 50ml', 6.50, 10, 6),
    ('Granules pour lave-vaisselle', 'Finish', 'Granules pour lave-vaisselle, 20 unités', 7.80, 5, 9),
    ('Chips', 'Pringles', 'Chips saveur barbecue, 200g', 2.80, 1, 2),
    ('Gelée de groseilles', 'Bonne Maman', 'Gelée de groseilles, 370g', 3.50, 1, 2),
    ('Éponge', 'Supermarché', 'Éponge absorbante, 2 unités', 1.90, 5, 9),
    ('Gant de bain', 'Supermarché', 'Gant de bain en loofah', 2.20, 10, 8),
    ('Poireaux surgelés', 'Supermarché', 'Poireaux surgelés, 1kg', 3.00, 3, 11),
    ('Café instantané', 'Nescafé', 'Café instantané, 100g', 4.20, 1, 2),
    ('Lait de riz', 'Alpro', 'Lait de riz, 1L', 2.70, 3, 1),
    ('Chocolat au lait', 'Côte d''Or', 'Tablette de chocolat au lait, 100g', 2.80, 1, 2),
    ('Bière brune', 'Guinness', 'Bière brune, 4x33cl', 6.50, 7, 5),
    ('Éponge à récurer', 'Supermarché', 'Éponge à récurer, 3 unités', 2.00, 5, 9),
    ('Crème brûlée', 'Caprice des Dieux', 'Crème brûlée, 4 unités', 4.00, 1, 2),
    ('Petits pois', 'Bonduelle', 'Petits pois en conserve, 400g', 1.50, 3, 2),
    ('Fromage râpé', 'Président', 'Fromage râpé, 200g', 2.90, 3, 1),
    ('Gelée de pommes', 'Andros', 'Gelée de pommes, 450g', 2.60, 1, 2),
    ('Eau gazeuse', 'San Pellegrino', 'Eau gazeuse, 1L', 1.20, 7, 4),
    ('Lait entier', 'Candia', 'Lait entier, 1L', 1.00, 3, 1),
    ('Chocolat au lait', 'Nestlé', 'Tablette de chocolat au lait entier, 100g', 2.40, 1, 2),
    ('Sirop d''érable', 'Maple Farm', 'Sirop d''érable pur, 250ml', 5.90, 1, 2),
    ('Riz complet', 'Tilda', 'Riz complet, 500g', 3.70, 3, 2),
    ('Crème de marrons', 'Clément Faugier', 'Crème de marrons, 500g', 4.20, 1, 2),
    ('Bâtonnets de surimi', 'Fleury Michon', 'Bâtonnets de surimi, 200g', 3.00, 3, 3),
    ('Lait concentré', 'Nestlé', 'Lait concentré sucré, 397g', 2.80, 3, 1),
    ('Pain pita', 'Supermarché', 'Pain pita, 6 unités', 2.50, 1, 2),
    ('Trousse de maquillage', 'Supermarché', 'Trousse de maquillage en cuir', 8.00, 10, 8),
    ('Confiture d''orange', 'Bonne Maman', 'Confiture d''orange, 370g', 3.40, 1, 2),
    ('Gaufrettes', 'LU', 'Gaufrettes chocolat, 200g', 2.90, 1, 2),
    ('Gel douche', 'Le Petit Marseillais', 'Gel douche au lait d''amande, 250ml', 3.00, 10, 6),
    ('Petits pois et carottes', 'Bonduelle', 'Petits pois et carottes, 400g', 1.80, 3, 2),
    ('Café moulu', 'Carte Noire', 'Café moulu, 250g', 4.50, 1, 2),
    ('Vinaigre de cidre', 'Braggs', 'Vinaigre de cidre, 500ml', 3.00, 1, 2),
    ('Cigarettes', 'Marlboro', 'Cigarettes, paquet de 20', 7.00, 9, 13),
    ('Papier de soie', 'Supermarché', 'Papier de soie, 10 feuilles', 1.80, 5, 9),
    ('Crêpes', 'Duc de Gascogne', 'Crêpes sucrées, 10 unités', 3.80, 1, 2),
    ('Sac poubelle', 'Supermarché', 'Sac poubelle, 30L', 1.80, 5, 9),
    ('Pâtes à tartiner', 'Chocolat Bonnat', 'Pâte à tartiner noisettes, 250g', 4.50, 1, 2),
    ('Papier cuisson', 'Supermarché', 'Papier cuisson, 15m', 2.00, 5, 9),
    ('Savon pour les mains', 'Le Petit Marseillais', 'Savon liquide pour les mains, 300ml', 2.90, 10, 6),
    ('Lait d''avoine', 'Oatly', 'Lait d''avoine, 1L', 2.50, 3, 1),
    ('Désodorisant', 'Air Wick', 'Désodorisant spray, 300ml', 3.10, 5, 8),
    ('Pâte brisée', 'Croustipate', 'Pâte brisée, 1 unité', 2.50, 1, 2),
    ('Tortillas', 'Old El Paso', 'Tortillas, 8 unités', 3.20, 1, 2),
    ('Lait d''avoine', 'Alpro', 'Lait d''avoine, 1L', 2.50, 3, 1),
    ('Papier toilette', 'Supermarché', 'Papier toilette, 12 rouleaux', 4.50, 5, 9),
    ('Pain de mie', 'Brioche Pasquier', 'Pain de mie, 500g', 2.50, 1, 2),
    ('Gant de bain', 'Supermarché', 'Gant de bain en coton', 2.20, 10, 8),
    ('Savon', 'Le Petit Marseillais', 'Savon solide au miel, 200g', 2.50, 10, 6),
    ('Fromage à raclette', 'Président', 'Fromage à raclette, 300g', 3.90, 3, 1),
    ('Conserve de tomates', 'Mutti', 'Conserve de tomates pelées, 400g', 2.20, 3, 2),
    ('Savon pour les mains', 'Dove', 'Savon liquide pour les mains, 300ml', 3.20, 10, 6),
    ('Spaghetti', 'Barilla', 'Spaghetti, 500g', 1.80, 3, 2),
    ('Chocolat noir', 'Lindt', 'Tablette de chocolat noir, 100g', 3.20, 1, 2),
    ('Amandes en poudre', 'Vahiné', 'Amandes en poudre, 200g', 3.00, 1, 2),
    ('Café moulu', 'Lavazza', 'Café moulu, 250g', 4.00, 1, 2),
    ('Confiture de fraises', 'Bonne Maman', 'Confiture de fraises, 370g', 3.40, 1, 2),
    ('Gaufres', 'LU', 'Gaufres à la framboise, 6 unités', 3.20, 1, 2),
    ('Amandes en poudre', 'Vahiné', 'Amandes en poudre, 200g', 3.00, 1, 2);