INSERT INTO Client (Nom,Prenom,Pt_Fidelite,Age,Mail,Num_Tel,Username,Password) VALUES
    ('Martin', 'Marie', 0, 28, 'marie.martin@mail.com', '0602030405','MMartin','f02368945726d5fc2a14eb576f7276c0'), --bonjour
    ('Bernard', 'Paul', 0, 42, 'paul.bernard@mail.com', '0603040506','PBernard','f02368945726d5fc2a14eb576f7276c0'), --bonjour
    ('Dubois', 'Pierre', 0, 31, 'pierre.dubois@mail.com', '0604050607','PDubois','ab4f63f9ac65152575886860dde480a1'), --azerty
    ('Durand', 'Luc', 0, 45, 'luc.durand@mail.com', '0605060708','LDurand','ab4f63f9ac65152575886860dde480a1'), --azerty
    ('Lefevre', 'Sophie', 0, 29, 'sophie.lefevre@mail.com', '0606070809','SLefevre','ab4f63f9ac65152575886860dde480a1'),  --azerty
    ('Moreau', 'Pierre', 0, 39, 'pierre.moreau@mail.com', '0607080910','PMoreau','70d4539ead3248bd4b79ede8ad3954ea'), --shreckislove
    ('Simon', 'Claire', 0, 33, 'claire.simon@mail.com', '0608091011','CSimon','70d4539ead3248bd4b79ede8ad3954ea'), --shreckislove
    ('Laurent', 'Nicolas', 0, 27, 'nicolas.laurent@mail.com', '0609101112','NLaurent','70d4539ead3248bd4b79ede8ad3954ea'); --shreckislove

INSERT INTO Admin (Nom,Prenom,Username,Password) VALUES
    ('Dupont', 'Jean', 'JDupont', '21232f297a57a5a743894a0e4a801fc3'); -- admin

INSERT INTO Paiement VALUES
    (1, 'Carte bancaire'),
    (2, 'Chèque'),
    (3, 'Espèces');

    
INSERT INTO Categorie VALUES
    (1, 'Alimentation', 'Fruits et légumes'),
    (2, 'Alimentation', 'Viande et volaille'),
    (3, 'Alimentation', 'Poissons et fruits de mer'),
    (4, 'Alimentation', 'Produits laitiers'),
    (5, 'Alimentation', 'Boulangerie'),
    (6, 'Alimentation', 'Épicerie salée'),
    (7, 'Alimentation', 'Épicerie sucrée'),
    (8, 'Alimentation', 'Surgelés'),
    (9, 'Alimentation', 'Boissons'),
    (10, 'Beauté et santé', 'Soins du visage'),
    (11, 'Beauté et santé', 'Soins du corps'),
    (12, 'Beauté et santé', 'Soins des cheveux'),
    (13, 'Beauté et santé', 'Maquillage'),
    (14, 'Beauté et santé', 'Parfums'),
    (15, 'Beauté et santé', 'Hygiène'),
    (16, 'Beauté et santé', 'Médicaments'),
    (17, 'Maison et jardin', 'Décoration'),
    (18, 'Maison et jardin', 'Meubles'),
    (19, 'Maison et jardin', 'Luminaires'),
    (20, 'Maison et jardin', 'Textile de maison'),
    (21, 'Maison et jardin', 'Cuisine et salle de bain'),
    (22, 'Maison et jardin', 'Rangement'),
    (23, 'Maison et jardin', 'Jardinage'),
    (24, 'Maison et jardin', 'Bricolage'),
    (25, 'Mode et accessoires', 'Vêtements femme'),
    (26, 'Mode et accessoires', 'Vêtements homme'),
    (27, 'Mode et accessoires', 'Vêtements enfant'),
    (28, 'Mode et accessoires', 'Chaussures'),
    (29, 'Mode et accessoires', 'Sacs et bagages'),
    (30, 'Mode et accessoires', 'Bijoux et montres'),
    (31, 'Mode et accessoires', 'Accessoires de mode'),
    (32, 'Électronique et informatique', 'Téléphones et accessoires'),
    (33, 'Électronique et informatique', 'Ordinateurs et tablettes'),
    (34, 'Électronique et informatique', 'Image et son'),
    (35, 'Électronique et informatique', 'Jeux vidéo et consoles'),
    (36, 'Électronique et informatique', 'Électroménager'),
    (37, 'Culture et loisirs', 'Livres'),
    (38, 'Culture et loisirs', 'Musique'),
    (39, 'Culture et loisirs', 'Films et séries'),
    (40, 'Culture et loisirs', 'Jeux et jouets'),
    (41, 'Culture et loisirs', 'Instruments de musique'),
    (42, 'Sport et plein air', 'Vêtements et chaussures de sport'),
    (43, 'Sport et plein air', 'Équipements sportifs'),
    (44, 'Sport et plein air', 'Camping et randonnée'),
    (45, 'Sport et plein air', 'Cyclisme'),
    (46, 'Sport et plein air', 'Sports nautiques'),
    (47, 'Bébé et enfant', 'Puériculture'),
    (48, 'Bébé et enfant', 'Jouets bébé'),
    (49, 'Bébé et enfant', 'Vêtements bébé'),
    (50, 'Animalerie', 'Alimentation animale'),
    (51, 'Animalerie', 'Accessoires pour animaux'),
    (52, 'Animalerie', 'Soins pour animaux');

INSERT INTO Description (Nom,Marque,Description,Prix,Num_Categorie) VALUES
    -- Fruits et légumes
    ('Pomme', 'Pink Lady', 'Pommes croquantes et sucrées', 3.50, 1),
    ('Banane', 'Chiquita', 'Bananes mûres et savoureuses', 2.20, 1),
    ('Tomate', 'Cœur de Bœuf', 'Tomates juteuses et charnues', 4.00, 1),
    ('Carotte', 'Bio Village', 'Carottes bio croquantes', 1.80, 1),
    ('Salade', 'Florette', 'Salade verte fraîche', 1.50, 1),
    ('Orange', 'Jaffa', 'Oranges juteuses et sucrées', 3.00, 1),
    ('Poire', 'Conférence', 'Poires fondantes et sucrées', 2.80, 1),
    ('Raisin', 'Muscat', 'Raisins noirs sucrés', 3.70, 1),
    ('Fraise', 'Gariguette', 'Fraises parfumées et sucrées', 5.00, 1),
    ('Pêche', 'Jaune', 'Pêches juteuses et sucrées', 4.20, 1),

    -- Viande et volaille
    ('Poulet', 'Loué', 'Poulet fermier Label Rouge', 8.50, 2),
    ('Bœuf', 'Charal', 'Steak haché pur bœuf', 6.00, 2),
    ('Porc', 'Herta', 'Côtes de porc', 5.50, 2),
    ('Agneau', 'Le Fin Gras', 'Côtelettes d''agneau', 12.00, 2),
    ('Dinde', 'Maître Coq', 'Escalopes de dinde', 7.00, 2),
    ('Canard', 'Rougié', 'Magret de canard', 15.00, 2),
    ('Veau', 'Blason Prestige', 'Escalopes de veau', 14.00, 2),
    ('Lapin', 'Duc', 'Cuisses de lapin', 10.00, 2),
    ('Saucisse', 'Jean Caby', 'Saucisses de Toulouse', 4.50, 2),
    ('Jambon', 'Fleury Michon', 'Jambon blanc supérieur', 3.80, 2),

    -- Poissons et fruits de mer
    ('Saumon', 'Labeyrie', 'Saumon fumé tranché', 12.00, 3),
    ('Thon', 'Petit Navire', 'Thon en boîte', 3.00, 3),
    ('Crevettes', 'Madagascar', 'Crevettes roses cuites', 9.00, 3),
    ('Cabillaud', 'Findus', 'Filets de cabillaud', 7.50, 3),
    ('Sardines', 'Connétable', 'Sardines à l''huile d''olive', 4.00, 3),
    ('Moules', 'Bouchot', 'Moules de bouchot', 5.00, 3),
    ('Huîtres', 'Gillardeau', 'Huîtres fines de claire', 15.00, 3),
    ('Calamars', 'Pescanova', 'Anneaux de calamars', 8.00, 3),
    ('Truite', 'Arc-en-ciel', 'Filets de truite', 6.50, 3),
    ('Homard', 'Bretagne', 'Homard bleu', 25.00, 3),

    -- Produits laitiers
    ('Lait', 'Candia', 'Lait entier', 1.20, 4),
    ('Yaourt', 'Yoplait', 'Yaourt nature', 2.00, 4),
    ('Fromage', 'Président', 'Camembert', 3.50, 4),
    ('Beurre', 'Elle & Vire', 'Beurre doux', 2.50, 4),
    ('Crème', 'Bridélice', 'Crème fraîche épaisse', 2.00, 4),
    ('Fromage blanc', 'Gervais', 'Fromage blanc 0%', 2.20, 4),
    ('Lait fermenté', 'Lactel', 'Lait Ribot', 1.80, 4),
    ('Mozzarella', 'Galbani', 'Mozzarella di Bufala', 3.00, 4),
    ('Parmesan', 'Parmigiano Reggiano', 'Parmesan râpé', 4.00, 4),
    ('Petit suisse', 'Nestlé', 'Petit suisse nature', 2.50, 4),

    -- Boulangerie
    ('Pain', 'Poilâne', 'Pain de campagne', 4.00, 5),
    ('Baguette', 'Tradition', 'Baguette tradition', 1.20, 5),
    ('Croissant', 'Maison', 'Croissant au beurre', 1.50, 5),
    ('Pain au chocolat', 'Maison', 'Pain au chocolat', 1.50, 5),
    ('Brioche', 'Pasquier', 'Brioche tranchée', 3.00, 5),
    ('Pain complet', 'Harrys', 'Pain complet tranché', 2.50, 5),
    ('Pain de mie', 'Jacquet', 'Pain de mie nature', 2.00, 5),
    ('Galette', 'St Michel', 'Galette bretonne', 3.50, 5),
    ('Tarte', 'Marie', 'Tarte aux pommes', 5.00, 5),
    ('Biscotte', 'Heudebert', 'Biscottes nature', 2.50, 5),

    -- Épicerie salée
    ('Pâtes', 'Barilla', 'Spaghetti n°5', 1.50, 6),
    ('Riz', 'Taureau Ailé', 'Riz basmati', 3.00, 6),
    ('Lentilles', 'Cassegrain', 'Lentilles cuisinées', 2.50, 6),
    ('Haricots', 'Bonduelle', 'Haricots verts extra-fins', 2.00, 6),
    ('Maïs', 'Green Giant', 'Maïs doux', 1.80, 6),
    ('Pois chiches', 'D’aucy', 'Pois chiches cuits', 2.00, 6),
    ('Olives', 'Crespo', 'Olives vertes dénoyautées', 2.50, 6),
    ('Sauce tomate', 'Panzani', 'Sauce tomate basilic', 2.00, 6),
    ('Thon', 'Petit Navire', 'Thon à l''huile d''olive', 3.50, 6),
    ('Cornichons', 'Amora', 'Cornichons extra-fins', 2.50, 6),

    -- Épicerie sucrée
    ('Confiture', 'Bonne Maman', 'Confiture de fraises', 3.50, 7),
    ('Miel', 'Lune de Miel', 'Miel de fleurs', 4.00, 7),
    ('Chocolat', 'Nestlé', 'Chocolat noir', 2.50, 7),
    ('Biscuits', 'Lu', 'Petits écoliers', 2.80, 7),
    ('Céréales', 'Kellogg''s', 'Corn Flakes', 3.00, 7),
    ('Bonbons', 'Haribo', 'Tagada', 2.50, 7),
    ('Gâteaux', 'BN', 'BN chocolat', 2.50, 7),
    ('Pâte à tartiner', 'Nutella', 'Pâte à tartiner noisettes', 4.00, 7),
    ('Compote', 'Andros', 'Compote de pommes', 2.50, 7),
    ('Sirop', 'Teisseire', 'Sirop de grenadine', 3.00, 7),

    -- Surgelés
    ('Pizza', 'Buitoni', 'Pizza 4 fromages', 4.50, 8),
    ('Glace', 'Häagen-Dazs', 'Glace vanille', 5.00, 8),
    ('Légumes', 'Bonduelle', 'Mélange de légumes', 3.00, 8),
    ('Frites', 'McCain', 'Frites surgelées', 2.50, 8),
    ('Poisson pané', 'Findus', 'Poisson pané croustillant', 4.00, 8),
    ('Lasagnes', 'Marie', 'Lasagnes bolognaises', 5.00, 8),
    ('Croquettes', 'Findus', 'Croquettes de poisson', 3.50, 8),
    ('Sorbet', 'Carte d''Or', 'Sorbet citron', 4.50, 8),
    ('Épinards', 'Bonduelle', 'Épinards hachés', 2.50, 8),
    ('Quiche', 'Marie', 'Quiche lorraine', 4.00, 8),

    -- Boissons
    ('Eau', 'Evian', 'Eau minérale naturelle', 1.00, 9),
    ('Jus d''orange', 'Tropicana', 'Jus d''orange sans pulpe', 3.00, 9),
    ('Soda', 'Coca-Cola', 'Soda au cola', 1.50, 9),
    ('Thé', 'Lipton', 'Thé glacé', 2.00, 9),
    ('Café', 'Nespresso', 'Capsules de café', 4.00, 9),
    ('Lait', 'Candia', 'Lait demi-écrémé', 1.20, 9),
    ('Vin', 'Bordeaux', 'Vin rouge', 8.00, 9),
    ('Bière', 'Heineken', 'Bière blonde', 1.50, 9),
    ('Eau gazeuse', 'Perrier', 'Eau gazeuse naturelle', 1.50, 9),
    ('Sirop', 'Teisseire', 'Sirop de menthe', 3.00, 9),

    -- Soins du visage
    ('Crème hydratante', 'Nivea', 'Crème hydratante pour le visage', 5.00, 10),
    ('Nettoyant visage', 'La Roche-Posay', 'Gel nettoyant purifiant', 8.00, 10),
    ('Masque', 'Garnier', 'Masque purifiant', 3.50, 10),
    ('Sérum', 'Vichy', 'Sérum anti-âge', 15.00, 10),
    ('Exfoliant', 'L''Oréal', 'Gommage exfoliant', 6.00, 10),
    ('Crème solaire', 'Avène', 'Crème solaire SPF 50', 12.00, 10),
    ('Contour des yeux', 'Clinique', 'Crème contour des yeux', 20.00, 10),
    ('Lotion tonique', 'Clarins', 'Lotion tonique apaisante', 10.00, 10),
    ('Huile démaquillante', 'DHC', 'Huile démaquillante', 25.00, 10),
    ('Eau micellaire', 'Bioderma', 'Eau micellaire démaquillante', 10.00, 10),
    -- Soins du corps
    ('Gel douche', 'Dove', 'Gel douche hydratant', 3.50, 11),
    ('Lait corporel', 'Nivea', 'Lait corporel nourrissant', 5.00, 11),
    ('Déodorant', 'Rexona', 'Déodorant anti-transpirant', 4.00, 11),
    ('Savon', 'Le Petit Marseillais', 'Savon liquide', 2.50, 11),
    ('Huile corporelle', 'Bio-Oil', 'Huile corporelle réparatrice', 10.00, 11),
    ('Crème pour les mains', 'Neutrogena', 'Crème mains réparatrice', 6.00, 11),
    ('Gommage corporel', 'Yves Rocher', 'Gommage corporel exfoliant', 8.00, 11),
    ('Lotion après-rasage', 'Nivea Men', 'Lotion après-rasage apaisante', 7.00, 11),
    ('Crème anti-cellulite', 'Elancyl', 'Crème anti-cellulite', 15.00, 11),
    ('Baume à lèvres', 'Labello', 'Baume à lèvres hydratant', 3.00, 11),

    -- Soins des cheveux
    ('Shampooing', 'Head & Shoulders', 'Shampooing antipelliculaire', 4.00, 12),
    ('Après-shampooing', 'L''Oréal', 'Après-shampooing nourrissant', 5.00, 12),
    ('Masque capillaire', 'Garnier', 'Masque capillaire réparateur', 6.00, 12),
    ('Sérum capillaire', 'Kérastase', 'Sérum capillaire lissant', 20.00, 12),
    ('Spray coiffant', 'Elnett', 'Spray coiffant fixation forte', 7.00, 12),
    ('Mousse coiffante', 'Schwarzkopf', 'Mousse coiffante volume', 6.00, 12),
    ('Gel coiffant', 'Taft', 'Gel coiffant fixation extrême', 5.00, 12),
    ('Huile capillaire', 'Moroccanoil', 'Huile capillaire nourrissante', 25.00, 12),
    ('Shampooing sec', 'Batiste', 'Shampooing sec rafraîchissant', 8.00, 12),
    ('Coloration', 'L''Oréal', 'Coloration permanente', 10.00, 12),

    -- Maquillage
    ('Fond de teint', 'Maybelline', 'Fond de teint liquide', 12.00, 13),
    ('Mascara', 'L''Oréal', 'Mascara volumateur', 10.00, 13),
    ('Rouge à lèvres', 'Chanel', 'Rouge à lèvres mat', 30.00, 13),
    ('Blush', 'Nars', 'Blush poudre', 25.00, 13),
    ('Eyeliner', 'Sephora', 'Eyeliner liquide', 15.00, 13),
    ('Fard à paupières', 'Urban Decay', 'Palette de fards à paupières', 40.00, 13),
    ('Crayon à sourcils', 'Benefit', 'Crayon à sourcils', 20.00, 13),
    ('Poudre libre', 'Laura Mercier', 'Poudre libre fixante', 35.00, 13),
    ('Correcteur', 'Tarte', 'Correcteur anti-cernes', 25.00, 13),
    ('Base de maquillage', 'Smashbox', 'Base de maquillage lissante', 30.00, 13),

    -- Parfums
    ('Eau de toilette', 'Dior', 'Eau de toilette pour homme', 60.00, 14),
    ('Eau de parfum', 'Chanel', 'Eau de parfum pour femme', 80.00, 14),
    ('Déodorant parfumé', 'Axe', 'Déodorant parfumé', 5.00, 14),
    ('Brume corporelle', 'Victoria''s Secret', 'Brume corporelle parfumée', 20.00, 14),
    ('Coffret parfum', 'Paco Rabanne', 'Coffret parfum et gel douche', 90.00, 14),
    ('Eau de Cologne', '4711', 'Eau de Cologne classique', 25.00, 14),
    ('Parfum solide', 'Diptyque', 'Parfum solide en pot', 50.00, 14),
    ('Eau fraîche', 'Hermès', 'Eau fraîche pour l''été', 70.00, 14),
    ('Parfum d''ambiance', 'Yankee Candle', 'Parfum d''ambiance en spray', 15.00, 14),
    ('Diffuseur de parfum', 'Esteban', 'Diffuseur de parfum pour la maison', 40.00, 14),

    -- Hygiène
    ('Dentifrice', 'Colgate', 'Dentifrice blancheur', 3.00, 15),
    ('Brosse à dents', 'Oral-B', 'Brosse à dents électrique', 25.00, 15),
    ('Fil dentaire', 'Oral-B', 'Fil dentaire ciré', 4.00, 15),
    ('Rasoir', 'Gillette', 'Rasoir jetable', 10.00, 15),
    ('Mousse à raser', 'Nivea Men', 'Mousse à raser apaisante', 5.00, 15),
    ('Shampooing', 'Head & Shoulders', 'Shampooing antipelliculaire', 4.00, 15),
    ('Gel douche', 'Dove', 'Gel douche hydratant', 3.50, 15),
    ('Déodorant', 'Rexona', 'Déodorant anti-transpirant', 4.00, 15),
    ('Savon', 'Le Petit Marseillais', 'Savon liquide', 2.50, 15),
    ('Lotion pour le corps', 'Nivea', 'Lotion hydratante', 5.00, 15),

    -- Médicaments
    ('Paracétamol', 'Doliprane', 'Paracétamol 500mg', 2.00, 16),
    ('Ibuprofène', 'Nurofen', 'Ibuprofène 400mg', 3.00, 16),
    ('Aspirine', 'Bayer', 'Aspirine 500mg', 2.50, 16),
    ('Antihistaminique', 'Zyrtec', 'Antihistaminique 10mg', 5.00, 16),
    ('Sirop pour la toux', 'Vicks', 'Sirop pour la toux', 4.00, 16),
    ('Pastilles pour la gorge', 'Strepsils', 'Pastilles pour la gorge', 3.50, 16),
    ('Gel anti-inflammatoire', 'Voltaren', 'Gel anti-inflammatoire', 6.00, 16),
    ('Crème antiseptique', 'Bepanthen', 'Crème antiseptique', 5.00, 16),
    ('Spray nasal', 'Physiomer', 'Spray nasal décongestionnant', 7.00, 16),
    ('Comprimés effervescents', 'Efferalgan', 'Comprimés effervescents', 4.00, 16),

    -- Décoration
    ('Bougie', 'Yankee Candle', 'Bougie parfumée', 20.00, 17),
    ('Cadre photo', 'Ikea', 'Cadre photo en bois', 10.00, 17),
    ('Vase', 'Maisons du Monde', 'Vase en céramique', 25.00, 17),
    ('Coussin', 'H&M Home', 'Coussin décoratif', 15.00, 17),
    ('Plaid', 'Zara Home', 'Plaid en laine', 30.00, 17),
    ('Lampe', 'Habitat', 'Lampe de table', 40.00, 17),
    ('Miroir', 'Maisons du Monde', 'Miroir mural', 50.00, 17),
    ('Rideaux', 'Ikea', 'Rideaux occultants', 35.00, 17),
    ('Tapis', 'Leroy Merlin', 'Tapis en jute', 60.00, 17),
    ('Horloge', 'Conforama', 'Horloge murale', 20.00, 17),

    -- Meubles
    ('Canapé', 'Ikea', 'Canapé 3 places', 300.00, 18),
    ('Table', 'Maisons du Monde', 'Table à manger', 200.00, 18),
    ('Chaise', 'Conforama', 'Chaise en bois', 50.00, 18),
    ('Lit', 'Ikea', 'Lit double', 400.00, 18),
    ('Armoire', 'Leroy Merlin', 'Armoire en bois', 500.00, 18),
    ('Commode', 'Habitat', 'Commode à tiroirs', 150.00, 18),
    ('Bureau', 'Ikea', 'Bureau en métal', 100.00, 18),
    ('Étagère', 'Conforama', 'Étagère murale', 80.00, 18),
    ('Fauteuil', 'Maisons du Monde', 'Fauteuil en tissu', 120.00, 18),
    ('Table basse', 'Ikea', 'Table basse en verre', 70.00, 18),
    -- Luminaires
    ('Lampe de chevet', 'Philips', 'Lampe de chevet LED', 25.00, 19),
    ('Plafonnier', 'Ikea', 'Plafonnier moderne', 50.00, 19),
    ('Applique murale', 'Maisons du Monde', 'Applique murale en métal', 30.00, 19),
    ('Guirlande lumineuse', 'Guirled', 'Guirlande lumineuse LED', 15.00, 19),
    ('Lampe de bureau', 'Anglepoise', 'Lampe de bureau articulée', 45.00, 19),
    ('Lampadaire', 'Habitat', 'Lampadaire trépied', 70.00, 19),
    ('Spot encastrable', 'Legrand', 'Spot encastrable LED', 20.00, 19),
    ('Suspension', 'Leroy Merlin', 'Suspension industrielle', 60.00, 19),
    ('Projecteur extérieur', 'Philips', 'Projecteur extérieur LED', 80.00, 19),
    ('Lampe solaire', 'Ikea', 'Lampe solaire de jardin', 25.00, 19),

    -- Textile de maison
    ('Draps', 'Dodo', 'Draps en coton', 30.00, 20),
    ('Couette', 'Ikea', 'Couette légère', 50.00, 20),
    ('Oreiller', 'Tempur', 'Oreiller ergonomique', 70.00, 20),
    ('Housse de couette', 'Linvosges', 'Housse de couette en lin', 80.00, 20),
    ('Serviette de bain', 'Descamps', 'Serviette de bain en éponge', 20.00, 20),
    ('Tapis de bain', 'Ikea', 'Tapis de bain antidérapant', 15.00, 20),
    ('Rideaux', 'Madura', 'Rideaux en velours', 60.00, 20),
    ('Plaid', 'Zara Home', 'Plaid en laine', 40.00, 20),
    ('Coussin', 'Maisons du Monde', 'Coussin décoratif', 25.00, 20),
    ('Nappe', 'Garnier-Thiebaut', 'Nappe en coton', 35.00, 20),

    -- Cuisine et salle de bain
    ('Casserole', 'Tefal', 'Casserole antiadhésive', 30.00, 21),
    ('Poêle', 'Lagostina', 'Poêle en inox', 40.00, 21),
    ('Mixeur', 'Moulinex', 'Mixeur plongeant', 50.00, 21),
    ('Robot de cuisine', 'Kenwood', 'Robot multifonction', 150.00, 21),
    ('Batterie de cuisine', 'Seb', 'Batterie de cuisine 10 pièces', 100.00, 21),
    ('Serviette de bain', 'Ikea', 'Serviette de bain en coton', 20.00, 21),
    ('Tapis de bain', 'Habitat', 'Tapis de bain antidérapant', 25.00, 21),
    ('Douchette', 'Grohe', 'Douchette à main', 35.00, 21),
    ('Miroir de salle de bain', 'Leroy Merlin', 'Miroir avec éclairage LED', 60.00, 21),
    ('Distributeur de savon', 'Umbra', 'Distributeur de savon automatique', 30.00, 21),

    -- Rangement
    ('Boîte de rangement', 'Ikea', 'Boîte de rangement en plastique', 10.00, 22),
    ('Étagère', 'Conforama', 'Étagère murale', 25.00, 22),
    ('Penderie', 'Maisons du Monde', 'Penderie en bois', 80.00, 22),
    ('Coffre de rangement', 'Habitat', 'Coffre de rangement en tissu', 40.00, 22),
    ('Panier à linge', 'Ikea', 'Panier à linge en osier', 20.00, 22),
    ('Boîte à chaussures', 'Leroy Merlin', 'Boîte à chaussures empilable', 15.00, 22),
    ('Organisateur de tiroir', 'Muji', 'Organisateur de tiroir en plastique', 10.00, 22),
    ('Porte-manteau', 'Conforama', 'Porte-manteau sur pied', 30.00, 22),
    ('Bibliothèque', 'Ikea', 'Bibliothèque en bois', 100.00, 22),
    ('Cintres', 'Ikea', 'Lot de 10 cintres en bois', 10.00, 22),

    -- Jardinage
    ('Plante verte', 'Truffaut', 'Plante verte d''intérieur', 20.00, 23),
    ('Terreau', 'Fertiligène', 'Terreau universel', 10.00, 23),
    ('Arrosoir', 'Gardena', 'Arrosoir en plastique', 15.00, 23),
    ('Sécateur', 'Fiskars', 'Sécateur à lames franches', 25.00, 23),
    ('Gants de jardinage', 'Wolf-Garten', 'Gants de jardinage en cuir', 20.00, 23),
    ('Tondeuse', 'Bosch', 'Tondeuse à gazon électrique', 150.00, 23),
    ('Brouette', 'Haemmerlin', 'Brouette en métal', 80.00, 23),
    ('Graines', 'Vilmorin', 'Graines de fleurs', 5.00, 23),
    ('Pelle', 'Leborgne', 'Pelle de jardin', 30.00, 23),
    ('Tuteur', 'Ikea', 'Tuteur en bambou', 10.00, 23),

    -- Bricolage
    ('Perceuse', 'Bosch', 'Perceuse sans fil', 100.00, 24),
    ('Marteau', 'Stanley', 'Marteau de charpentier', 20.00, 24),
    ('Tournevis', 'Facom', 'Tournevis à tête plate', 10.00, 24),
    ('Scie', 'Black & Decker', 'Scie sauteuse', 50.00, 24),
    ('Mètre ruban', 'Stanley', 'Mètre ruban 5m', 15.00, 24),
    ('Niveau à bulle', 'Bosch', 'Niveau à bulle magnétique', 25.00, 24),
    ('Visseuse', 'Makita', 'Visseuse sans fil', 80.00, 24),
    ('Pince multiprise', 'Knipex', 'Pince multiprise réglable', 30.00, 24),
    ('Clé à molette', 'Facom', 'Clé à molette ajustable', 25.00, 24),
    ('Coffret à outils', 'Stanley', 'Coffret à outils 50 pièces', 60.00, 24),

    -- Vêtements femme
    ('Robe', 'Zara', 'Robe en coton', 40.00, 25),
    ('Jean', 'Levi''s', 'Jean slim', 80.00, 25),
    ('Blouse', 'Mango', 'Blouse en soie', 50.00, 25),
    ('Jupe', 'H&M', 'Jupe plissée', 30.00, 25),
    ('T-shirt', 'Uniqlo', 'T-shirt en coton', 20.00, 25),
    ('Pull', 'Benetton', 'Pull en laine', 60.00, 25),
    ('Veste', 'Promod', 'Veste en jean', 70.00, 25),
    ('Manteau', 'Sandro', 'Manteau en laine', 150.00, 25),
    ('Pantalon', 'Zara', 'Pantalon en lin', 50.00, 25),
    ('Chemisier', 'Mango', 'Chemisier en soie', 40.00, 25),

    -- Vêtements homme
    ('Chemise', 'Celio', 'Chemise en coton', 40.00, 26),
    ('Jean', 'Levi''s', 'Jean droit', 80.00, 26),
    ('T-shirt', 'Lacoste', 'T-shirt en coton', 50.00, 26),
    ('Pull', 'Ralph Lauren', 'Pull en laine', 100.00, 26),
    ('Veste', 'Hugo Boss', 'Veste en cuir', 200.00, 26),
    ('Pantalon', 'Dockers', 'Pantalon chino', 60.00, 26),
    ('Blouson', 'Schott', 'Blouson en cuir', 250.00, 26),
    ('Manteau', 'Burberry', 'Manteau en laine', 300.00, 26),
    ('Short', 'Nike', 'Short de sport', 30.00, 26),
    ('Costume', 'Hugo Boss', 'Costume en laine', 400.00, 26),

    -- Vêtements enfant
    ('T-shirt', 'Petit Bateau', 'T-shirt en coton', 15.00, 27),
    ('Pantalon', 'Okaïdi', 'Pantalon en jean', 25.00, 27),
    ('Robe', 'Sergent Major', 'Robe en coton', 30.00, 27),
    ('Pull', 'Jacadi', 'Pull en laine', 40.00, 27),
    ('Veste', 'Vertbaudet', 'Veste en jean', 35.00, 27),
    ('Manteau', 'Catimini', 'Manteau en laine', 60.00, 27),
    ('Pyjama', 'Petit Bateau', 'Pyjama en coton', 20.00, 27),
    ('Short', 'Okaïdi', 'Short en jean', 20.00, 27),
    ('Chemise', 'Sergent Major', 'Chemise en coton', 25.00, 27),
    ('Jupe', 'Jacadi', 'Jupe plissée', 30.00, 27),

    -- Chaussures
    ('Baskets', 'Nike', 'Baskets de sport', 80.00, 28),
    ('Bottes', 'Aigle', 'Bottes en caoutchouc', 60.00, 28),
    ('Sandales', 'Birkenstock', 'Sandales en cuir', 50.00, 28),
    ('Chaussures de ville', 'Clarks', 'Chaussures en cuir', 100.00, 28),
    ('Espadrilles', 'Havaianas', 'Espadrilles en toile', 30.00, 28),
    ('Mocassins', 'Geox', 'Mocassins en cuir', 90.00, 28),
    ('Tongs', 'Ipanema', 'Tongs en plastique', 20.00, 28),
    ('Chaussures de randonnée', 'Salomon', 'Chaussures de randonnée imperméables', 120.00, 28),
    ('Chaussures de sécurité', 'Caterpillar', 'Chaussures de sécurité en cuir', 110.00, 28),
    ('Pantoufles', 'Isotoner', 'Pantoufles en tissu', 25.00, 28),

    -- Sacs et bagages
    ('Sac à dos', 'Eastpak', 'Sac à dos en toile', 50.00, 29),
    ('Valise', 'Samsonite', 'Valise rigide', 150.00, 29),
    ('Sac à main', 'Longchamp', 'Sac à main en cuir', 200.00, 29),
    ('Sac de sport', 'Nike', 'Sac de sport en polyester', 40.00, 29),
    ('Sac de voyage', 'Delsey', 'Sac de voyage en toile', 100.00, 29),
    ('Pochette', 'Guess', 'Pochette en cuir', 80.00, 29),
    ('Sac banane', 'Adidas', 'Sac banane en nylon', 30.00, 29),
    ('Sac à dos ordinateur', 'Targus', 'Sac à dos pour ordinateur portable', 60.00, 29),
    ('Sac à langer', 'Babymoov', 'Sac à langer multifonction', 70.00, 29),
    ('Sac de plage', 'Roxy', 'Sac de plage en paille', 40.00, 29),

    -- Bijoux et montres
    ('Montre', 'Casio', 'Montre digitale', 50.00, 30),
    ('Bracelet', 'Pandora', 'Bracelet en argent', 70.00, 30),
    ('Collier', 'Swarovski', 'Collier en cristal', 100.00, 30),
    ('Boucles d''oreilles', 'Agatha', 'Boucles d''oreilles en argent', 40.00, 30),
    ('Bague', 'Cartier', 'Bague en or', 500.00, 30),
    ('Pendentif', 'Tiffany & Co.', 'Pendentif en argent', 150.00, 30),
    ('Broche', 'Chanel', 'Broche en métal', 200.00, 30),
    ('Montre connectée', 'Apple', 'Montre connectée Apple Watch', 400.00, 30),
    ('Bracelet en cuir', 'Hermès', 'Bracelet en cuir', 300.00, 30),
    ('Collier de perles', 'Mikimoto', 'Collier de perles', 1000.00, 30),

    -- Accessoires de mode
    ('Écharpe', 'Hermès', 'Écharpe en soie', 200.00, 31),
    ('Ceinture', 'Gucci', 'Ceinture en cuir', 250.00, 31),
    ('Lunettes de soleil', 'Ray-Ban', 'Lunettes de soleil aviateur', 150.00, 31),
    ('Chapeau', 'Borsalino', 'Chapeau en feutre', 300.00, 31),
    ('Gants', 'Lacoste', 'Gants en laine', 50.00, 31),
    ('Portefeuille', 'Louis Vuitton', 'Portefeuille en cuir', 400.00, 31),
    ('Montre', 'Swatch', 'Montre analogique', 100.00, 31),
    ('Parapluie', 'Burberry', 'Parapluie à carreaux', 150.00, 31),
    ('Casquette', 'Adidas', 'Casquette de sport', 30.00, 31),
    ('Foulard', 'Chanel', 'Foulard en soie', 250.00, 31),

    -- Téléphones et accessoires
    ('Smartphone', 'Apple', 'iPhone 13', 900.00, 32),
    ('Coque de téléphone', 'Spigen', 'Coque de protection', 20.00, 32),
    ('Chargeur', 'Anker', 'Chargeur rapide', 30.00, 32),
    ('Écouteurs', 'Sony', 'Écouteurs sans fil', 150.00, 32),
    ('Support de téléphone', 'Belkin', 'Support de voiture', 25.00, 32),
    ('Batterie externe', 'Xiaomi', 'Batterie de secours', 40.00, 32),
    ('Câble USB', 'Samsung', 'Câble de recharge', 15.00, 32),
    ('Station de charge', 'Nomad', 'Station de charge multiple', 80.00, 32),
    ('Film protecteur', 'Zagg', 'Film en verre trempé', 20.00, 32),
    ('Stylet', 'Apple', 'Apple Pencil', 130.00, 32),

    -- Ordinateurs et tablettes
    ('Ordinateur portable', 'Dell', 'XPS 13', 1200.00, 33),
    ('Tablette', 'Apple', 'iPad Pro', 1000.00, 33),
    ('Clavier', 'Logitech', 'Clavier sans fil', 50.00, 33),
    ('Souris', 'Microsoft', 'Souris ergonomique', 40.00, 33),
    ('Housse de protection', 'Case Logic', 'Housse pour ordinateur', 30.00, 33),
    ('Disque dur externe', 'Seagate', 'Disque dur 1TB', 60.00, 33),
    ('Hub USB', 'Anker', 'Hub USB-C', 40.00, 33),
    ('Support pour ordinateur', 'Rain Design', 'Support en aluminium', 70.00, 33),
    ('Webcam', 'Logitech', 'Webcam HD', 80.00, 33),
    ('Écran', 'Samsung', 'Écran 27 pouces', 300.00, 33),

    -- Image et son
    ('Télévision', 'Samsung', 'Télévision 4K', 800.00, 34),
    ('Enceinte Bluetooth', 'JBL', 'Enceinte portable', 100.00, 34),
    ('Casque audio', 'Bose', 'Casque à réduction de bruit', 300.00, 34),
    ('Barre de son', 'Sony', 'Barre de son 5.1', 400.00, 34),
    ('Lecteur Blu-ray', 'LG', 'Lecteur Blu-ray 4K', 150.00, 34),
    ('Projecteur', 'Epson', 'Projecteur HD', 600.00, 34),
    ('Amplificateur', 'Yamaha', 'Amplificateur stéréo', 500.00, 34),
    ('Microphone', 'Blue', 'Microphone USB', 150.00, 34),
    ('Radio', 'Roberts', 'Radio numérique', 200.00, 34),
    ('Lecteur MP3', 'Apple', 'iPod Touch', 250.00, 34),

    -- Jeux vidéo et consoles
    ('Console de jeu', 'Sony', 'PlayStation 5', 500.00, 35),
    ('Manette de jeu', 'Microsoft', 'Manette Xbox', 60.00, 35),
    ('Jeu vidéo', 'Nintendo', 'The Legend of Zelda', 70.00, 35),
    ('Casque VR', 'Oculus', 'Oculus Quest 2', 300.00, 35),
    ('Carte mémoire', 'SanDisk', 'Carte microSD 128GB', 40.00, 35),
    ('Volant de course', 'Logitech', 'Volant G29', 250.00, 35),
    ('Station de recharge', 'PowerA', 'Station de recharge pour manettes', 30.00, 35),
    ('Support de jeu', 'Hori', 'Support de jeu pour Nintendo Switch', 20.00, 35),
    ('Clavier de jeu', 'Razer', 'Clavier mécanique', 150.00, 35),
    ('Souris de jeu', 'SteelSeries', 'Souris gaming', 80.00, 35),

    -- Électroménager
    ('Réfrigérateur', 'Samsung', 'Réfrigérateur américain', 1500.00, 36),
    ('Lave-vaisselle', 'Bosch', 'Lave-vaisselle encastrable', 700.00, 36),
    ('Machine à laver', 'LG', 'Machine à laver 8kg', 600.00, 36),
    ('Four', 'Whirlpool', 'Four encastrable', 500.00, 36),
    ('Micro-ondes', 'Panasonic', 'Micro-ondes combiné', 200.00, 36),
    ('Aspirateur', 'Dyson', 'Aspirateur sans fil', 400.00, 36),
    ('Cafetière', 'Nespresso', 'Machine à café', 150.00, 36),
    ('Grille-pain', 'Philips', 'Grille-pain 2 fentes', 50.00, 36),
    ('Mixeur', 'Moulinex', 'Mixeur plongeant', 60.00, 36),
    ('Bouilloire', 'Russell Hobbs', 'Bouilloire électrique', 40.00, 36),

    -- Livres
    ('Roman', 'Gallimard', 'L''Étranger', 10.00, 37),
    ('Bande dessinée', 'Dargaud', 'Astérix le Gaulois', 12.00, 37),
    ('Livre de cuisine', 'Hachette', 'Cuisine pour débutants', 20.00, 37),
    ('Livre pour enfants', 'Bayard', 'Le Petit Prince', 15.00, 37),
    ('Guide de voyage', 'Lonely Planet', 'Guide de Paris', 25.00, 37),
    ('Livre de poche', 'Pocket', 'Harry Potter à l''école des sorciers', 8.00, 37),
    ('Essai', 'Flammarion', 'Sapiens : Une brève histoire de l''humanité', 18.00, 37),
    ('Biographie', 'Fayard', 'Steve Jobs', 22.00, 37),
    ('Livre d''art', 'Taschen', 'L''Art de la Renaissance', 30.00, 37),
    ('Dictionnaire', 'Larousse', 'Dictionnaire français', 35.00, 37),

    -- Musique
    ('Album', 'Universal', 'Thriller - Michael Jackson', 15.00, 38),
    ('Vinyle', 'Sony Music', 'Abbey Road - The Beatles', 25.00, 38),
    ('CD', 'Warner Music', 'Back to Black - Amy Winehouse', 10.00, 38),
    ('Instrument de musique', 'Yamaha', 'Guitare acoustique', 200.00, 38),
    ('Partition', 'Hal Leonard', 'Partition de piano', 20.00, 38),
    ('Casque audio', 'Bose', 'Casque à réduction de bruit', 300.00, 38),
    ('Enceinte', 'JBL', 'Enceinte Bluetooth', 100.00, 38),
    ('Lecteur CD', 'Sony', 'Lecteur CD portable', 50.00, 38),
    ('Piano', 'Korg', 'Piano numérique', 500.00, 38),
    ('Microphone', 'Shure', 'Microphone dynamique', 150.00, 38),

    -- Films et séries
    ('DVD', 'Warner Bros', 'Le Seigneur des Anneaux', 20.00, 39),
    ('Blu-ray', 'Disney', 'La Reine des Neiges', 25.00, 39),
    ('Coffret', 'HBO', 'Game of Thrones - Intégrale', 100.00, 39),
    ('Film', 'Paramount', 'Titanic', 15.00, 39),
    ('Série TV', 'Netflix', 'Stranger Things - Saison 1', 30.00, 39),
    ('Documentaire', 'BBC', 'Planète Terre', 40.00, 39),
    ('Film d''animation', 'Pixar', 'Toy Story', 20.00, 39),
    ('Comédie', 'Universal', 'Les Bronzés', 15.00, 39),
    ('Thriller', 'Sony Pictures', 'Inception', 20.00, 39),
    ('Film d''action', '20th Century Fox', 'Die Hard', 15.00, 39),

    -- Jeux et jouets
    ('Jeu de société', 'Hasbro', 'Monopoly', 30.00, 40),
    ('Puzzle', 'Ravensburger', 'Puzzle 1000 pièces', 20.00, 40),
    ('Peluche', 'Disney', 'Peluche Mickey Mouse', 25.00, 40),
    ('Lego', 'Lego', 'Lego Star Wars', 80.00, 40),
    ('Jeu éducatif', 'Nathan', 'Jeu de lettres', 15.00, 40),
    ('Voiture télécommandée', 'Nikko', 'Voiture télécommandée', 50.00, 40),
    ('Jeu de construction', 'Meccano', 'Kit de construction', 40.00, 40),
    ('Jeu vidéo', 'Nintendo', 'Mario Kart', 60.00, 40),
    ('Déguisement', 'Rubie''s', 'Déguisement de super-héros', 30.00, 40),
    ('Trampoline', 'Jumpking', 'Trampoline de jardin', 200.00, 40),
    
    -- Instruments de musique
    ('Guitare électrique', 'Fender', 'Guitare électrique Stratocaster', 800.00, 41),
    ('Piano numérique', 'Yamaha', 'Piano numérique portable', 600.00, 41),
    ('Batterie', 'Pearl', 'Batterie acoustique', 1000.00, 41),
    ('Saxophone', 'Selmer', 'Saxophone alto', 1500.00, 41),
    ('Clarinette', 'Buffet Crampon', 'Clarinette en si bémol', 700.00, 41),
    ('Flûte traversière', 'Yamaha', 'Flûte traversière en argent', 500.00, 41),
    ('Violon', 'Stentor', 'Violon 4/4', 400.00, 41),
    ('Harmonica', 'Hohner', 'Harmonica diatonique', 50.00, 41),
    ('Accordéon', 'Hohner', 'Accordéon chromatique', 1200.00, 41),
    ('Trompette', 'Bach', 'Trompette en si bémol', 900.00, 41),

    -- Vêtements et chaussures de sport
    ('Chaussures de running', 'Nike', 'Chaussures de running Air Zoom', 120.00, 42),
    ('T-shirt de sport', 'Adidas', 'T-shirt de sport Climalite', 30.00, 42),
    ('Short de sport', 'Puma', 'Short de sport en polyester', 25.00, 42),
    ('Veste de sport', 'Under Armour', 'Veste de sport à capuche', 60.00, 42),
    ('Legging de sport', 'Reebok', 'Legging de sport ajusté', 40.00, 42),
    ('Brassière de sport', 'Nike', 'Brassière de sport Pro', 35.00, 42),
    ('Chaussettes de sport', 'Adidas', 'Chaussettes de sport en coton', 15.00, 42),
    ('Sac de sport', 'Nike', 'Sac de sport en toile', 50.00, 42),
    ('Casquette de sport', 'Under Armour', 'Casquette de sport ajustable', 20.00, 42),
    ('Gants de sport', 'Reebok', 'Gants de sport en cuir', 25.00, 42),

    -- Équipements sportifs
    ('Haltères', 'Domyos', 'Haltères en fonte', 30.00, 43),
    ('Tapis de yoga', 'Manduka', 'Tapis de yoga antidérapant', 60.00, 43),
    ('Vélo d''appartement', 'ProForm', 'Vélo d''appartement pliable', 300.00, 43),
    ('Banc de musculation', 'Weider', 'Banc de musculation ajustable', 150.00, 43),
    ('Corde à sauter', 'Domyos', 'Corde à sauter en nylon', 15.00, 43),
    ('Ballon de football', 'Adidas', 'Ballon de football officiel', 25.00, 43),
    ('Raquette de tennis', 'Babolat', 'Raquette de tennis en graphite', 100.00, 43),
    ('Gants de boxe', 'Everlast', 'Gants de boxe en cuir', 50.00, 43),
    ('Tapis de course', 'NordicTrack', 'Tapis de course motorisé', 800.00, 43),
    ('Kit de musculation', 'Domyos', 'Kit de musculation complet', 200.00, 43),

    -- Camping et randonnée
    ('Tente de camping', 'Quechua', 'Tente de camping 2 places', 100.00, 44),
    ('Sac de couchage', 'Decathlon', 'Sac de couchage en duvet', 80.00, 44),
    ('Sac à dos de randonnée', 'Osprey', 'Sac à dos de randonnée 50L', 150.00, 44),
    ('Chaussures de randonnée', 'Salomon', 'Chaussures de randonnée imperméables', 120.00, 44),
    ('Lampe de poche', 'Maglite', 'Lampe de poche LED', 30.00, 44),
    ('Réchaud de camping', 'Campingaz', 'Réchaud de camping portable', 50.00, 44),
    ('Matelas de sol', 'Therm-a-Rest', 'Matelas de sol autogonflant', 70.00, 44),
    ('Boussole', 'Silva', 'Boussole de randonnée', 20.00, 44),
    ('Gourde', 'Nalgene', 'Gourde en plastique', 15.00, 44),
    ('Poncho de pluie', 'Quechua', 'Poncho de pluie imperméable', 25.00, 44),

    -- Cyclisme
    ('Vélo de route', 'Giant', 'Vélo de route en carbone', 1500.00, 45),
    ('Casque de vélo', 'Bell', 'Casque de vélo aérodynamique', 100.00, 45),
    ('Gants de cyclisme', 'Gore', 'Gants de cyclisme en gel', 30.00, 45),
    ('Maillot de cyclisme', 'Castelli', 'Maillot de cyclisme respirant', 80.00, 45),
    ('Cuissard de cyclisme', 'Rapha', 'Cuissard de cyclisme rembourré', 120.00, 45),
    ('Pompe à vélo', 'Topeak', 'Pompe à vélo portable', 25.00, 45),
    ('Lumière de vélo', 'Lezyne', 'Lumière de vélo LED', 40.00, 45),
    ('Antivol de vélo', 'Kryptonite', 'Antivol de vélo en U', 50.00, 45),
    ('Bidon de vélo', 'Elite', 'Bidon de vélo en plastique', 10.00, 45),
    ('Compteur de vélo', 'Garmin', 'Compteur de vélo GPS', 200.00, 45),

    -- Sports nautiques
    ('Planche de surf', 'Quiksilver', 'Planche de surf en fibre de verre', 300.00, 46),
    ('Combinaison de plongée', 'Rip Curl', 'Combinaison de plongée en néoprène', 150.00, 46),
    ('Palmes', 'Cressi', 'Palmes de plongée', 50.00, 46),
    ('Masque de plongée', 'Mares', 'Masque de plongée avec tuba', 40.00, 46),
    ('Gilet de sauvetage', 'Tribord', 'Gilet de sauvetage homologué', 60.00, 46),
    ('Kayak', 'Bic Sport', 'Kayak gonflable', 400.00, 46),
    ('Stand up paddle', 'Red Paddle Co', 'Planche de stand up paddle', 500.00, 46),
    ('Wakeboard', 'Jobe', 'Planche de wakeboard', 250.00, 46),
    ('Gants de plongée', 'Beuchat', 'Gants de plongée en néoprène', 30.00, 46),
    ('Sac étanche', 'Overboard', 'Sac étanche pour sports nautiques', 40.00, 46),

    -- Puériculture
    ('Poussette', 'Bébé Confort', 'Poussette compacte et légère', 200.00, 47),
    ('Siège auto', 'Cybex', 'Siège auto évolutif', 150.00, 47),
    ('Lit parapluie', 'Chicco', 'Lit parapluie pliable', 100.00, 47),
    ('Transat', 'BabyBjörn', 'Transat pour bébé', 80.00, 47),
    ('Chaise haute', 'Stokke', 'Chaise haute évolutive', 150.00, 47),
    ('Trotteur', 'Vtech', 'Trotteur interactif', 50.00, 47),
    ('Baignoire bébé', 'Babymoov', 'Baignoire pliable', 40.00, 47),
    ('Babyphone', 'Philips Avent', 'Babyphone avec caméra', 100.00, 47),
    ('Coussin d''allaitement', 'Doomoo', 'Coussin d''allaitement ergonomique', 60.00, 47),
    ('Table à langer', 'Ikea', 'Table à langer murale', 80.00, 47),

    -- Jouets bébé
    ('Hochet', 'Fisher-Price', 'Hochet coloré', 10.00, 48),
    ('Doudou', 'Doudou et Compagnie', 'Doudou en peluche', 20.00, 48),
    ('Tapis d''éveil', 'Tiny Love', 'Tapis d''éveil interactif', 50.00, 48),
    ('Mobile musical', 'Vtech', 'Mobile musical pour lit bébé', 40.00, 48),
    ('Cubes empilables', 'Janod', 'Cubes empilables en bois', 30.00, 48),
    ('Livre en tissu', 'Lilliputiens', 'Livre en tissu pour bébé', 20.00, 48),
    ('Anneau de dentition', 'Sophie la girafe', 'Anneau de dentition en caoutchouc', 15.00, 48),
    ('Peluche musicale', 'Kaloo', 'Peluche musicale douce', 25.00, 48),
    ('Jeu de bain', 'Munchkin', 'Jeu de bain flottant', 15.00, 48),
    ('Voiture à tirer', 'Vilac', 'Voiture à tirer en bois', 30.00, 48),

    -- Vêtements bébé
    ('Body', 'Petit Bateau', 'Body en coton bio', 10.00, 49),
    ('Pyjama', 'Absorba', 'Pyjama en velours', 15.00, 49),
    ('Salopette', 'Sergent Major', 'Salopette en jean', 20.00, 49),
    ('Bonnet', 'Catimini', 'Bonnet en laine', 8.00, 49),
    ('Chaussons', 'Vertbaudet', 'Chaussons en cuir', 12.00, 49),
    ('Gigoteuse', 'Red Castle', 'Gigoteuse en coton', 25.00, 49),
    ('Combinaison', 'Tartine et Chocolat', 'Combinaison en polaire', 30.00, 49),
    ('T-shirt', 'Jacadi', 'T-shirt en coton bio', 10.00, 49),
    ('Pantalon', 'Okaïdi', 'Pantalon en velours', 15.00, 49),
    ('Robe', 'DPAM', 'Robe en coton', 20.00, 49),

    -- Alimentation animale
    ('Croquettes pour chien', 'Royal Canin', 'Croquettes équilibrées pour chien adulte', 50.00, 50),
    ('Croquettes pour chat', 'Purina', 'Croquettes pour chat stérilisé', 40.00, 50),
    ('Pâtée pour chien', 'Pedigree', 'Pâtée en sauce pour chien', 25.00, 50),
    ('Pâtée pour chat', 'Whiskas', 'Pâtée en gelée pour chat', 20.00, 50),
    ('Friandises pour chien', 'Frolic', 'Friandises moelleuses pour chien', 15.00, 50),
    ('Friandises pour chat', 'Dreamies', 'Friandises croquantes pour chat', 10.00, 50),
    ('Croquettes pour chiot', 'Hill''s', 'Croquettes pour chiot en croissance', 45.00, 50),
    ('Croquettes pour chaton', 'Royal Canin', 'Croquettes pour chaton', 35.00, 50),
    ('Os à mâcher', 'Pedigree', 'Os à mâcher pour chien', 12.00, 50),
    ('Lait pour chaton', 'Whiskas', 'Lait maternisé pour chaton', 8.00, 50),

    -- Accessoires pour animaux
    ('Collier pour chien', 'Hunter', 'Collier en cuir pour chien', 25.00, 51),
    ('Laisse pour chien', 'Flexi', 'Laisse rétractable pour chien', 20.00, 51),
    ('Arbre à chat', 'Trixie', 'Arbre à chat en sisal', 60.00, 51),
    ('Panier pour chien', 'Ferplast', 'Panier en plastique pour chien', 30.00, 51),
    ('Panier pour chat', 'Zolux', 'Panier en tissu pour chat', 25.00, 51),
    ('Gamelle pour chien', 'Savic', 'Gamelle en inox pour chien', 15.00, 51),
    ('Gamelle pour chat', 'Ferplast', 'Gamelle en céramique pour chat', 12.00, 51),
    ('Jouet pour chien', 'Kong', 'Jouet en caoutchouc pour chien', 10.00, 51),
    ('Jouet pour chat', 'Catit', 'Jouet interactif pour chat', 15.00, 51),
    ('Brosse pour chien', 'Furminator', 'Brosse de toilettage pour chien', 20.00, 51),

    -- Soins pour animaux
    ('Shampooing pour chien', 'Biogance', 'Shampooing doux pour chien', 10.00, 52),
    ('Shampooing pour chat', 'Beaphar', 'Shampooing doux pour chat', 10.00, 52),
    ('Antiparasitaire pour chien', 'Frontline', 'Antiparasitaire pour chien', 30.00, 52),
    ('Antiparasitaire pour chat', 'Advantage', 'Antiparasitaire pour chat', 25.00, 52),
    ('Dentifrice pour chien', 'Virbac', 'Dentifrice pour chien', 8.00, 52),
    ('Dentifrice pour chat', 'Beaphar', 'Dentifrice pour chat', 8.00, 52),
    ('Lotion pour les yeux', 'Trixie', 'Lotion nettoyante pour les yeux', 12.00, 52),
    ('Lotion pour les oreilles', 'Virbac', 'Lotion nettoyante pour les oreilles', 12.00, 52),
    ('Spray démêlant', 'Biogance', 'Spray démêlant pour chien', 15.00, 52),
    ('Spray anti-puces', 'Frontline', 'Spray anti-puces pour chat', 20.00, 52);